// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class PetsAdoptionPrediction
{
    /// <summary>
    /// model input class for PetsAdoptionPrediction.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(1)]
        [ColumnName(@"PetType")]
        public string PetType { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Breed")]
        public string Breed { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"AgeMonths")]
        public float AgeMonths { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"Size")]
        public string Size { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"Vaccinated")]
        public float Vaccinated { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"HealthCondition")]
        public float HealthCondition { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"TimeInShelterDays")]
        public float TimeInShelterDays { get; set; }

        [LoadColumn(12)]
        [ColumnName(@"AdoptionLikelihood")]
        public float AdoptionLikelihood { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for PetsAdoptionPrediction.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"PetType")]
        public float[] PetType { get; set; }

        [ColumnName(@"Breed")]
        public float[] Breed { get; set; }

        [ColumnName(@"AgeMonths")]
        public float AgeMonths { get; set; }

        [ColumnName(@"Size")]
        public float[] Size { get; set; }

        [ColumnName(@"Vaccinated")]
        public float Vaccinated { get; set; }

        [ColumnName(@"HealthCondition")]
        public float HealthCondition { get; set; }

        [ColumnName(@"TimeInShelterDays")]
        public float TimeInShelterDays { get; set; }

        [ColumnName(@"AdoptionLikelihood")]
        public float AdoptionLikelihood { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("PetsAdoptionPrediction.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
